//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageGallery.Core.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ImageGallery.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string AlreadyHaveAccount {
            get {
                return ResourceManager.GetString("AlreadyHaveAccount", resourceCulture);
            }
        }

        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }

        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }

        public static string E_CanNotFindPropertyInJson {
            get {
                return ResourceManager.GetString("E_CanNotFindPropertyInJson", resourceCulture);
            }
        }

        public static string E_ConnectionFailed {
            get {
                return ResourceManager.GetString("E_ConnectionFailed", resourceCulture);
            }
        }

        public static string E_JsonCanNotBeEmpy {
            get {
                return ResourceManager.GetString("E_JsonCanNotBeEmpy", resourceCulture);
            }
        }

        public static string E_ServerError {
            get {
                return ResourceManager.GetString("E_ServerError", resourceCulture);
            }
        }

        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        public static string U_Cancel {
            get {
                return ResourceManager.GetString("U_Cancel", resourceCulture);
            }
        }
        
        public static string U_Retry {
            get {
                return ResourceManager.GetString("U_Retry", resourceCulture);
            }
        }
        
        public static string SingUp {
            get {
                return ResourceManager.GetString("SingUp", resourceCulture);
            }
        }
        
        public static string V_Email {
            get {
                return ResourceManager.GetString("V_Email", resourceCulture);
            }
        }
        
        public static string V_Image {
            get {
                return ResourceManager.GetString("V_Image", resourceCulture);
            }
        }
        
        public static string V_Password {
            get {
                return ResourceManager.GetString("V_Password", resourceCulture);
            }
        }
        
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
